### ISSUE TITLE
Document calling validation from an external application

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/validate#18]
#2 refactors the code so that it can be called by an external application. Add a section to the README after "Running the project" titled "Calling Validate from external applications" with a description of the `ErrorListener` interface and the various `validate` methods.

@kayr would be great if you could take this one! 😊

**Comment by mitchellsundt** [comment]
Note that ODK Validate already is run by the online XLSForm converter on the opendatakit.org site. Any changes should be verified to not impact that usage, or to modify the usage so that this functionality is not broken.  

The XLSForm online repos are at:

https://github.com/uw-ictd/pyxform_interface

And, I forget whether the following repo is in use or if we are pulling from the main pyxform repo now:

https://github.com/uw-ictd/pyxform

**Comment by kayr** [comment]
Thanx for the heads-up,
I have tested from command line `java -jar validate.jar path/to/xform.xml` and got output with no UI.
Double clicking the jar launched the UI. So usage should remain as before via the command-line interface.

**Comment by lognaturel** [comment]
Thank you, @mitchellsundt, I made sure it wouldn't break https://github.com/XLSForm/pyxform but I totally forgot about the online tool. It looks like it calls out to pyxform directly so we're ok. Thanks for that extra check @kayr.
